import streamlit as st

st.set_page_config(
    page_title="ResumeAI — Smart Hiring Assistant",
    page_icon="📄",
    layout="wide",
)

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.stApp { background: #0a0f1e; color: #e8eaf0; }
#MainMenu, footer { visibility: hidden; }
.block-container { padding-top: 2rem; max-width: 1100px; }
section[data-testid="stSidebar"] { background: #0d1321; border-right: 1px solid #1e2d40; }

.hero { text-align: center; padding: 4rem 2rem 2rem; }
.hero-eyebrow { font-family: 'Space Grotesk', sans-serif; font-size: 0.75rem; font-weight: 600; letter-spacing: 0.15em; text-transform: uppercase; color: #00d4b4; margin-bottom: 1rem; }
.hero-title { font-family: 'Space Grotesk', sans-serif; font-size: 3.2rem; font-weight: 700; line-height: 1.1; color: #ffffff; margin-bottom: 1rem; }
.hero-title span { color: #00d4b4; }
.hero-subtitle { font-size: 1.1rem; color: #8892a4; max-width: 580px; margin: 0 auto 2.5rem; line-height: 1.7; font-weight: 300; }

.card-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; margin: 2rem 0; }
.card { background: #111827; border: 1px solid #1e2d40; border-radius: 16px; padding: 2rem; position: relative; overflow: hidden; }
.card::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px; background: linear-gradient(90deg, #00d4b4, #0099ff); }
.card-icon { font-size: 2rem; margin-bottom: 1rem; }
.card-title { font-family: 'Space Grotesk', sans-serif; font-size: 1.1rem; font-weight: 600; color: #ffffff; margin-bottom: 0.6rem; }
.card-desc { font-size: 0.875rem; color: #6b7a92; line-height: 1.6; margin-bottom: 1.2rem; }
.card-nav { font-size: 0.8rem; font-weight: 500; color: #00d4b4; }

.divider { border: none; border-top: 1px solid #1e2d40; margin: 2.5rem 0; }
.how-title { font-family: 'Space Grotesk', sans-serif; font-size: 1.4rem; font-weight: 600; color: #ffffff; margin-bottom: 1.5rem; text-align: center; }
.steps { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; margin-bottom: 2.5rem; }
.step { background: #111827; border: 1px solid #1e2d40; border-radius: 12px; padding: 1.5rem; display: flex; gap: 1rem; align-items: flex-start; }
.step-num { font-family: 'Space Grotesk', sans-serif; font-size: 1.5rem; font-weight: 700; color: #00d4b4; line-height: 1; min-width: 2rem; }
.step-text strong { display: block; font-size: 0.9rem; font-weight: 600; color: #e8eaf0; margin-bottom: 0.3rem; }
.step-text span { font-size: 0.8rem; color: #6b7a92; line-height: 1.5; }

.tech-grid { display: flex; flex-wrap: wrap; gap: 0.6rem; justify-content: center; }
.tech-pill { background: #1a2535; border: 1px solid #1e2d40; border-radius: 100px; padding: 0.35rem 1rem; font-size: 0.78rem; color: #8892a4; font-weight: 500; }
.section-label { font-family: 'Space Grotesk', sans-serif; font-size: 0.7rem; font-weight: 600; letter-spacing: 0.12em; text-transform: uppercase; color: #3d5166; text-align: center; margin-bottom: 1rem; }

.sidebar-logo { font-family: 'Space Grotesk', sans-serif; font-size: 1.1rem; font-weight: 700; color: #00d4b4; padding: 0.5rem 0 1.5rem; }
.sidebar-section { font-size: 0.7rem; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; color: #3d5166; margin: 1.2rem 0 0.6rem; }
.sidebar-tip { background: #111827; border: 1px solid #1e2d40; border-radius: 10px; padding: 0.8rem 1rem; font-size: 0.78rem; color: #6b7a92; line-height: 1.5; margin-bottom: 0.5rem; }
.sidebar-tip strong { color: #e8eaf0; display: block; margin-bottom: 0.2rem; }
</style>
""", unsafe_allow_html=True)

with st.sidebar:
    st.markdown('<div class="sidebar-logo">📄 ResumeAI</div>', unsafe_allow_html=True)
    st.markdown("**AI-Powered Hiring Intelligence**")
    st.caption("Built with Python, Streamlit, NLP, and Generative AI.")
    st.divider()

    st.markdown('<div class="sidebar-section">Navigate</div>', unsafe_allow_html=True)
    st.markdown("🔍 **Resume Screening** — Match your resume to a JD")
    st.markdown("📊 **Batch Screening** — Rank multiple candidates")
    st.markdown("🎤 **Interview Prep** — Get personalized questions")

    st.divider()
    st.markdown('<div class="sidebar-section">About this project</div>', unsafe_allow_html=True)
    st.markdown('<div class="sidebar-tip"><strong>NLP Pipeline</strong>Skill extraction, semantic matching, and gap analysis using sentence-transformers.</div>', unsafe_allow_html=True)
    st.markdown('<div class="sidebar-tip"><strong>Generative AI</strong>Interview questions generated by LLaMA 3.3 70B via Groq API.</div>', unsafe_allow_html=True)
    st.markdown('<div class="sidebar-tip"><strong>OCR Support</strong>JDs can be uploaded as PDF or image screenshots using Tesseract OCR.</div>', unsafe_allow_html=True)

    st.divider()
    st.markdown('<div class="sidebar-section">Tech stack</div>', unsafe_allow_html=True)
    st.caption("Python · Streamlit · pdfplumber · sentence-transformers · Groq · pytesseract · scikit-learn")

st.markdown("""
<div class="hero">
    <div class="hero-eyebrow">AI-Powered Hiring Intelligence</div>
    <div class="hero-title">Match smarter.<br><span>Hire better.</span></div>
    <div class="hero-subtitle">Upload a resume and job description — get instant match scores, skill gap analysis, and personalized interview questions powered by NLP and generative AI.</div>
</div>

<div class="card-grid">
    <div class="card">
        <div class="card-icon">🔍</div>
        <div class="card-title">Resume Screening</div>
        <div class="card-desc">Upload your resume and a job description. Get an instant match score, skill gap breakdown, and actionable improvement suggestions.</div>
        <div class="card-nav">← Resume Screening in sidebar</div>
    </div>
    <div class="card">
        <div class="card-icon">📊</div>
        <div class="card-title">Batch Screening</div>
        <div class="card-desc">Recruiters: upload multiple resumes against one JD and get a ranked candidate table sorted by AI match score instantly.</div>
        <div class="card-nav">← Batch Screening in sidebar</div>
    </div>
    <div class="card">
        <div class="card-icon">🎤</div>
        <div class="card-title">Interview Prep</div>
        <div class="card-desc">Get 5–10 personalized interview questions generated by AI, tailored specifically to your resume and the role you're applying for.</div>
        <div class="card-nav">← Interview Prep in sidebar</div>
    </div>
</div>

<hr class="divider">

<div class="how-title">How it works</div>
<div class="steps">
    <div class="step">
        <div class="step-num">1</div>
        <div class="step-text">
            <strong>Parse & Extract</strong>
            <span>NLP extracts skills, experience, and education from your resume and JD automatically.</span>
        </div>
    </div>
    <div class="step">
        <div class="step-num">2</div>
        <div class="step-text">
            <strong>Match & Score</strong>
            <span>Semantic similarity + skill overlap scoring produces an explainable match percentage.</span>
        </div>
    </div>
    <div class="step">
        <div class="step-num">3</div>
        <div class="step-text">
            <strong>Prepare & Improve</strong>
            <span>AI generates personalized interview questions and targeted improvement suggestions.</span>
        </div>
    </div>
</div>

<div class="section-label">Built with</div>
<div class="tech-grid">
    <span class="tech-pill">Python</span>
    <span class="tech-pill">Streamlit</span>
    <span class="tech-pill">pdfplumber</span>
    <span class="tech-pill">sentence-transformers</span>
    <span class="tech-pill">Groq LLaMA 3.3</span>
    <span class="tech-pill">pytesseract OCR</span>
    <span class="tech-pill">scikit-learn</span>
</div>
""", unsafe_allow_html=True)
